#!/bin/bash

PERCENTAGE="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percentage' | awk '{print $2}')"
STATE="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'state' | awk '{print $2}')"

VALUE=${PERCENTAGE%?}

CHARGING_ICONS=("󰢟" "󰢜" "󰂆" "󰂇" "󰂈" "󰢝" "󰂉" "󰢞" "󰂊" "󰂋" "󰂅") 
DISCHARGING_ICONS=("󱃍" "󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹") 

if [ "$STATE" = "charging" ] || [ "$STATE" = "pending-charge" ]; then
    ICON=${CHARGING_ICONS[${VALUE%?}]}
else
    ICON=${DISCHARGING_ICONS[${VALUE%?}]}
fi

echo "${ICON}${PERCENTAGE}"
